### ISSUE TITLE
makecmd from README doesn't work

### ISSUE THREAD

**Issue by gnull** [krornus/kakoune-cargo#1]
Shouldn't it be

```
set-option window makecmd 'cargo build'
```

in README? Running just `cargo` gives help text.

**Comment by krornus** [comment]
I have it as cargo so you can run
`:make build`
or
`:make run`
or any other cargo command you may want inside of kak, maybe I can note that in the docs though

**Comment by gnull** [comment]
Ah! That makes sense, I didn't know one can use `:make` like this. Thanks a lot!
